export default Object.freeze({
  LISTING: "LISTING",
  LISTING_DETAILS: "LISTING_DETAILS",
  LISTING_EDIT: "LISTING_EDIT",

  //   Auth routes
  WELCOME: "WELCOME",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",

  // Account
  ACCOUNT: "ACCOUNT",
  MESSAGES: "MESSAGES",
});
